version: "3"

networks:
  private:
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  db_data:
  jenkins_data:
  wp_data:


services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      private:
        ipv4_address: 172.18.0.10

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      private:
        ipv4_address: 172.18.0.11
  
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    restart: always
    volumes:
      - wp_data:/var/www/html
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}      
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      private:
        ipv4_address: 172.18.0.12


